CREATE TABLE "WhatsappSettings" (
  "shop" TEXT NOT NULL PRIMARY KEY,
  "phone" TEXT,
  "message" TEXT,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
